In [15]:
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)

In [16]:
#Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
#to print the data types of both the variables.

In [17]:
#yes there is a difference

In [18]:
print('data type of list_ is->',type(list_[1]))

data type of list_ is-> <class 'str'>


In [25]:
print('data type of array_list is->',array_list[0].dtype)

data type of array_list is-> <U1


In [20]:
#Q2. Write a code to print the data type of each and every element of both the variables list_ and
#arra_list.

In [22]:
for i in list_:
    print(f'element-{i} data type is-> ',type(i))

element-1 data type is->  <class 'str'>
element-2 data type is->  <class 'str'>
element-3 data type is->  <class 'str'>
element-4 data type is->  <class 'str'>
element-5 data type is->  <class 'str'>


In [23]:
for i in array_list:
      print(f'element-{i} data type is-> ',type(i))

element-1 data type is->  <class 'numpy.str_'>
element-2 data type is->  <class 'numpy.str_'>
element-3 data type is->  <class 'numpy.str_'>
element-4 data type is->  <class 'numpy.str_'>
element-5 data type is->  <class 'numpy.str_'>


In [26]:
#Q3. Considering the following changes in the variable, array_list:
#array_list = np.array(object = list_, dtype = int)
#Will there be any difference in the data type of the elements present in both the variables, list_ and
#arra_list? If so then print the data types of each and every element present in both the variables, list_
#and arra_list.

In [27]:
array_list = np.array(object = list_, dtype = int)

In [28]:
array_list

array([1, 2, 3, 4, 5])

In [29]:
print('data type of list_ is->',type(list_[1]))

data type of list_ is-> <class 'str'>


In [31]:
print('data type of array_list is->',array_list.dtype)

data type of array_list is-> int64


In [32]:
#Q4. Write a code to find the following characteristics of variable, num_array:
#(i) shape
#(ii) size

In [33]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [35]:
print('shape of the num_array is->',num_array.shape)

shape of the num_array is-> (2, 3)


In [36]:
print('size of the num_array is->',num_array.size)

size of the num_array is-> 6


In [37]:
#Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
#creation function.
#[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [46]:
np1=np.zeros((3,3))

In [47]:
np1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [49]:
#Q6. Create an identity matrix of shape (5,5) using numpy functions?
#[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [50]:
np2=np.eye(5)

In [51]:
np2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])